on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: 7bf262014b72ca4b73ee588d0fef98399ff2347e3a82565923ed605ae9e949fd

    env:
      # postgres://user:password@host:port/database
      DATABASE_URL: "postgres://idiodloisdyejk:7bf262014b72ca4b73ee588d0fef98399ff2347e3a82565923ed605ae9e949fd@ec2-44-194-183-115.compute-1.amazonaws.com:5432/d5vbibgi9faqdb"

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
